# Generated by Django 5.1.1 on 2024-09-28 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_mailorder_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailorder',
            old_name='nombres',
            new_name='nombre',
        ),
    ]
