# Generated by Django 5.1.1 on 2024-10-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_nombres_mailorder_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailorder',
            name='phone',
            field=models.TextField(null=True),
        ),
    ]
