# Generated by Django 5.1.1 on 2024-10-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenproducto',
            name='image_src',
            field=models.TextField(default='/'),
        ),
    ]
