# Generated by Django 5.1.1 on 2024-10-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_imagenproducto_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='product_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
